version: "3"

services:

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Madrid
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
#      - WATCHTOWER_NOTIFICATIONS=email
#      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=from@gmail.com
#      - WATCHTOWER_NOTIFICATION_EMAIL_TO=to@gmail.com
#      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
#      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=password
#      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=Server Container Updates
#      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=from@gmail.com
#      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587 
    restart: unless-stopped

        